version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Map your local port to the container's port

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ausentismo
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306" # Map your local port to the container's port
